-- LUXORA cloud setup for Supabase
-- Run this once in Supabase SQL Editor.

-- Products table (safe if it already exists)
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null default 0,
  description text default '',
  category text default 'classic',
  image_url text default '',
  badge text default '',
  stock integer not null default 0,
  created_at timestamptz default now()
);

alter table public.products enable row level security;

-- Browser permissions: everyone can read; only signed-in admins can write.
grant select on public.products to anon, authenticated;
grant insert, update, delete on public.products to authenticated;

drop policy if exists "Public can view products" on public.products;
create policy "Public can view products" on public.products
for select to anon, authenticated using (true);

drop policy if exists "Admins can insert products" on public.products;
create policy "Admins can insert products" on public.products
for insert to authenticated with check (true);

drop policy if exists "Admins can update products" on public.products;
create policy "Admins can update products" on public.products
for update to authenticated using (true) with check (true);

drop policy if exists "Admins can delete products" on public.products;
create policy "Admins can delete products" on public.products
for delete to authenticated using (true);

-- Public image bucket for product photos.
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = true;

drop policy if exists "Public can view LUXORA product images" on storage.objects;
create policy "Public can view LUXORA product images" on storage.objects
for select to public using (bucket_id = 'product-images');

drop policy if exists "Admins can upload LUXORA product images" on storage.objects;
create policy "Admins can upload LUXORA product images" on storage.objects
for insert to authenticated with check (bucket_id = 'product-images');

drop policy if exists "Admins can update LUXORA product images" on storage.objects;
create policy "Admins can update LUXORA product images
" on storage.objects
for update to authenticated using (bucket_id = 'product-images') with check (bucket_id = 'product-images');

drop policy if exists "Admins can delete LUXORA product images" on storage.objects;
create policy "Admins can delete LUXORA product images" on storage.objects
for delete to authenticated using (bucket_id = 'product-images');

-- Optional starter products: only insert if table is empty.
insert into public.products (name, price, description, category, image_url, badge, stock)
select * from (values
  ('LUXORA Noir',17900,'قرص أسود عميق مع هيكل فولاذي مصقول، مصممة لمن يحب الحضور الهادئ.','classic','','الأكثر طلباً',10),
  ('LUXORA Silver',21900,'تصميم فضي نظيف بقرص فاتح وتفاصيل دقيقة لإطلالة يومية فاخرة.','classic','','جديد',8),
  ('LUXORA Gold',25900,'لمسات ذهبية مع قرص Midnight داكن. قطعة محدودة لمحبي التفاصيل الجريئة.','limited','','LIMITED',3),
  ('LUXORA Chrono',28900,'طابع رياضي فاخر وهيكل قوي مستوحى من ساعات الأداء العالي.','sport','','SPORT',6),
  ('LUXORA Eclipse',23900,'تصميم أسود بالكامل بلمسة معدنية خافتة، مثالية للمناسبات المسائية.','classic','','',9),
  ('LUXORA Titan',32900,'هيكل قوي وتفاصيل حادة لعشاق الساعات ذات الشخصية الواضحة.','sport','','PREMIUM',5)
) as v(name,price,description,category,image_url,badge,stock)
where not exists (select 1 from public.products);
